# Generated by Django 6.0.1 on 2026-02-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('municipal', 'Municipal'), ('water', 'Water Department'), ('traffic', 'Traffic Police'), ('fire', 'Fire Department')], max_length=20, null=True),
        ),
    ]
