# Generated by Django 6.0 on 2026-02-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, choices=[('model_town', 'Model Town'), ('civil_lines', 'Civil Lines'), ('cantonment', 'Cantonment'), ('city_center', 'City Center'), ('industrial_area', 'Industrial Area')], max_length=20, null=True),
        ),
    ]
