# Generated by Django 6.0 on 2026-02-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, help_text="Officer's jurisdiction area (e.g., 'Ahmedabad')", max_length=100, null=True),
        ),
    ]
