# Generated by Django 6.0 on 2026-02-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.CharField(blank=True, choices=[('municipal', 'Municipal Corporation'), ('water', 'Water Department'), ('traffic', 'Traffic Police'), ('fire', 'Fire Department')], max_length=20),
        ),
    ]
