# Generated by Django 5.2.6 on 2026-02-12 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_fine_amount_complaint_fine_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, help_text='AI confidence score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_language',
            field=models.CharField(default='en', help_text='Language used for AI validation', max_length=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_validation_passed',
            field=models.BooleanField(blank=True, help_text='Whether AI validation passed', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_validation_result',
            field=models.TextField(blank=True, help_text='AI validation response'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('correct', 'AI was correct'), ('incorrect', 'AI was incorrect'), ('unsure', 'Not sure')], max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Additional user comments')),
                ('ai_said_valid', models.BooleanField(help_text='What AI concluded')),
                ('user_thinks_valid', models.BooleanField(help_text='What user actually thinks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedbacks', to='complaints.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Feedback',
                'verbose_name_plural': 'AI Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIValidationMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_type', models.CharField(help_text='Type: parking, road, garbage', max_length=20)),
                ('ai_detected', models.BooleanField(help_text='What AI detected (True=issue found)')),
                ('ai_confidence', models.FloatField(help_text='Confidence score 0-100')),
                ('ai_response', models.TextField(help_text='Full AI response text')),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='AI processing time in milliseconds', null=True)),
                ('api_model_used', models.CharField(default='llama-3.2-11b-vision-preview', max_length=50)),
                ('user_agreed', models.BooleanField(blank=True, help_text='Did user agree with AI assessment?', null=True)),
                ('user_feedback_text', models.TextField(blank=True, help_text="User's feedback on AI accuracy")),
                ('officer_verified', models.BooleanField(blank=True, help_text="Officer's verification of complaint", null=True)),
                ('officer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_metrics', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'AI Validation Metric',
                'verbose_name_plural': 'AI Validation Metrics',
                'ordering': ['-created_at'],
            },
        ),
    ]
