# Generated by Django 5.2.6 on 2026-02-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_fine_amount_complaint_fine_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ai_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
